changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - cloudeteerbot
  categories:
    - title: Breaking Changes 💥
      labels:
        - breaking
    - title: New Features ✨
      labels:
        - feature
    - title: Bug Fixes 🐛
      labels:
        - fix
    - title: Documentation Changes 📝
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
